export default {
    products: [
        {
            _id: '1',
            name: 'ziped nike shirt',
            category: 'shirt',
            image: 'images/product-1.jpg',
            price: 49,
            brand: 'nike',
            rating: 2.5,
            numberReviews: 20,
            countInStock: 10,
            description: 'Nice, dressier Tshirt. Cute flutter sleeves. The shirt itself has a bit of an A-line shape, so it’s not tight on the belly for those of us carrying a few extra pounds in that area. Rounded hemline is flattering tucked in or out. Not overly long like most shirts are these days: I’m 5’2” and the hem hit me mid-butt, which is perfect: I hate shirts that hang past my butt unless I’m wearing yoga pants or leggings, which I seldomely wear in public: I’m a jeans girl! The chest fit me well, but I’m a 36C: you might want to size up if you’re bigger busted. The heathered look is more pronounced in the picture than in person: very subtle, hardly noticeable in person, atleast in the apricot color that I ordered. Overall, this top is lightweight and very flattering for most body types I would think. Washed up well with no shrinkage, but I only dried it halfway and hung it to dry the rest of the way as I do with all of my shirts and sweaters.',
        },
        {
            _id: '2',
            name: 'Square Neck Petal Sleeve Tshirts Black S',
            category: 'shirt',
            image: 'images/product-2.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
            description: 'Nice, dressier Tshirt. Cute flutter sleeves. The shirt itself has a bit of an A-line shape, so it’s not tight on the belly for those of us carrying a few extra pounds in that area. Rounded hemline is flattering tucked in or out. Not overly long like most shirts are these days: I’m 5’2” and the hem hit me mid-butt, which is perfect: I hate shirts that hang past my butt unless I’m wearing yoga pants or leggings, which I seldomely wear in public: I’m a jeans girl! The chest fit me well, but I’m a 36C: you might want to size up if you’re bigger busted. The heathered look is more pronounced in the picture than in person: very subtle, hardly noticeable in person, atleast in the apricot color that I ordered. Overall, this top is lightweight and very flattering for most body types I would think. Washed up well with no shrinkage, but I only dried it halfway and hung it to dry the rest of the way as I do with all of my shirts and sweaters.',
        },
        {
            _id: '3',
            name: 'Coconut Tree Graphic Vest',
            category: 'shirt',
            image: 'images/product-3.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
            description: 'Nice, dressier Tshirt. Cute flutter sleeves. The shirt itself has a bit of an A-line shape, so it’s not tight on the belly for those of us carrying a few extra pounds in that area. Rounded hemline is flattering tucked in or out. Not overly long like most shirts are these days: I’m 5’2” and the hem hit me mid-butt, which is perfect: I hate shirts that hang past my butt unless I’m wearing yoga pants or leggings, which I seldomely wear in public: I’m a jeans girl! The chest fit me well, but I’m a 36C: you might want to size up if you’re bigger busted. The heathered look is more pronounced in the picture than in person: very subtle, hardly noticeable in person, atleast in the apricot color that I ordered. Overall, this top is lightweight and very flattering for most body types I would think. Washed up well with no shrinkage, but I only dried it halfway and hung it to dry the rest of the way as I do with all of my shirts and sweaters.',
        },
        {
            _id: '4',
            name: 'Sleeveless Casual Basic',
            category: 'shirt',
            image: 'images/product-4.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
            description: 'Nice, dressier Tshirt. Cute flutter sleeves. The shirt itself has a bit of an A-line shape, so it’s not tight on the belly for those of us carrying a few extra pounds in that area. Rounded hemline is flattering tucked in or out. Not overly long like most shirts are these days: I’m 5’2” and the hem hit me mid-butt, which is perfect: I hate shirts that hang past my butt unless I’m wearing yoga pants or leggings, which I seldomely wear in public: I’m a jeans girl! The chest fit me well, but I’m a 36C: you might want to size up if you’re bigger busted. The heathered look is more pronounced in the picture than in person: very subtle, hardly noticeable in person, atleast in the apricot color that I ordered. Overall, this top is lightweight and very flattering for most body types I would think. Washed up well with no shrinkage, but I only dried it halfway and hung it to dry the rest of the way as I do with all of my shirts and sweaters.',
        },
        {
            _id: '5',
            name: 'Square Neck Loose Fit',
            category: 'shirt',
            image: 'images/product-5.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
            description: 'Nice, dressier Tshirt. Cute flutter sleeves. The shirt itself has a bit of an A-line shape, so it’s not tight on the belly for those of us carrying a few extra pounds in that area. Rounded hemline is flattering tucked in or out. Not overly long like most shirts are these days: I’m 5’2” and the hem hit me mid-butt, which is perfect: I hate shirts that hang past my butt unless I’m wearing yoga pants or leggings, which I seldomely wear in public: I’m a jeans girl! The chest fit me well, but I’m a 36C: you might want to size up if you’re bigger busted. The heathered look is more pronounced in the picture than in person: very subtle, hardly noticeable in person, atleast in the apricot color that I ordered. Overall, this top is lightweight and very flattering for most body types I would think. Washed up well with no shrinkage, but I only dried it halfway and hung it to dry the rest of the way as I do with all of my shirts and sweaters.',
        },
        {
            _id: '6',
            name: 'Tops Racerback Athletic Yoga',
            category: 'shirt',
            image: 'images/product-6.webp',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
            description: 'Nice, dressier Tshirt. Cute flutter sleeves. The shirt itself has a bit of an A-line shape, so it’s not tight on the belly for those of us carrying a few extra pounds in that area. Rounded hemline is flattering tucked in or out. Not overly long like most shirts are these days: I’m 5’2” and the hem hit me mid-butt, which is perfect: I hate shirts that hang past my butt unless I’m wearing yoga pants or leggings, which I seldomely wear in public: I’m a jeans girl! The chest fit me well, but I’m a 36C: you might want to size up if you’re bigger busted. The heathered look is more pronounced in the picture than in person: very subtle, hardly noticeable in person, atleast in the apricot color that I ordered. Overall, this top is lightweight and very flattering for most body types I would think. Washed up well with no shrinkage, but I only dried it halfway and hung it to dry the rest of the way as I do with all of my shirts and sweaters.',
        },
        {
            _id: '7',
            name: 'Fashion Sleeveless Top Loose',
            category: 'shirt',
            image: 'images/product-7.webp',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
            description: 'Nice, dressier Tshirt. Cute flutter sleeves. The shirt itself has a bit of an A-line shape, so it’s not tight on the belly for those of us carrying a few extra pounds in that area. Rounded hemline is flattering tucked in or out. Not overly long like most shirts are these days: I’m 5’2” and the hem hit me mid-butt, which is perfect: I hate shirts that hang past my butt unless I’m wearing yoga pants or leggings, which I seldomely wear in public: I’m a jeans girl! The chest fit me well, but I’m a 36C: you might want to size up if you’re bigger busted. The heathered look is more pronounced in the picture than in person: very subtle, hardly noticeable in person, atleast in the apricot color that I ordered. Overall, this top is lightweight and very flattering for most body types I would think. Washed up well with no shrinkage, but I only dried it halfway and hung it to dry the rest of the way as I do with all of my shirts and sweaters.',
        },
    ],
}
