export default {
    products: [
        {
            _id: '1',
            name: 'ziped nike shirt',
            category: 'shirt',
            image: 'images/product-1.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
        },
        {
            _id: '2',
            name: 'ziped nike shirt',
            category: 'shirt',
            image: 'images/product-1.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
        },
        {
            _id: '3',
            name: 'ziped nike shirt',
            category: 'shirt',
            image: 'images/product-1.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
        },
        {
            _id: '4',
            name: 'ziped nike shirt',
            category: 'shirt',
            image: 'images/product-1.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
        },
        {
            _id: '5',
            name: 'ziped nike shirt',
            category: 'shirt',
            image: 'images/product-1.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
        },
        {
            _id: '6',
            name: 'ziped nike shirt',
            category: 'shirt',
            image: 'images/product-1.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
        },
        {
            _id: '7',
            name: 'ziped nike shirt',
            category: 'shirt',
            image: 'images/product-1.jpg',
            price: 49,
            brand: 'nike',
            rating: 4.5,
            numberReviews: 10,
            countInStock: 10,
        },
    ],
}
